---
# tasks file for SMPlayer
- name: Install Prerequisites
  apt:
    pkg: "{{ smplayer_prerequisites }}"
    state: "present"
    update_cache: "yes"

- name: Create SMPlayer Directories in {{ SMPLAYER_SOURCE_PREFIX }}
  file:
    path: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item }}"
    state: "directory"
  with_items:
    - "{{ SMPLAYER_SOURCE }}"
    - "{{ SMPLAYER_THEMES_SOURCE }}"
    - "{{ SMPLAYER_SKINS_SOURCE }}"

- name: Download SMPlayer Tarballs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item.dest }}"
  with_items:
    - { url: "{{ SMPLAYER_TARBALL_URL }}", dest: "{{ SMPLAYER_TARBALL }}" }
    - { url: "{{ SMPLAYER_THEMES_TARBALL_URL }}", dest: "{{ SMPLAYER_THEMES_TARBALL }}" }
    - { url: "{{ SMPLAYER_SKINS_TARBALL_URL }}", dest: "{{ SMPLAYER_SKINS_TARBALL }}" }

- name: Extract SMPlayer Tarballs
  unarchive:
    src: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item.src }}"
    dest: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item.dest }}"
    extra_opts: "--strip-components=1"
  with_items:
    - { src: "{{ SMPLAYER_TARBALL }}", dest: "{{ SMPLAYER_SOURCE }}" }
    - { src: "{{ SMPLAYER_THEMES_TARBALL }}", dest: "{{ SMPLAYER_THEMES_SOURCE }}" }
    - { src: "{{ SMPLAYER_SKINS_TARBALL }}", dest: "{{ SMPLAYER_SKINS_SOURCE }}" }

- name: Create SMPlayer DEB Packages from Source
  shell: |
    ./create_deb.sh
  args:
    executable: "/bin/bash"
    chdir: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item }}"
  with_items:
    - "{{ SMPLAYER_SOURCE }}"
    - "{{ SMPLAYER_THEMES_SOURCE }}"
    - "{{ SMPLAYER_SKINS_SOURCE }}"

- name: Install SMPlayer DEB Packages
  shell: "dpkg --install {{ item }}"
  args:
    executable: "/bin/bash"
    chdir: "{{ SMPLAYER_SOURCE_PREFIX }}"
  with_items:
    - "{{ SMPLAYER_DEB }}"
    - "{{ SMPLAYER_THEMES_DEB }}"
    - "{{ SMPLAYER_SKINS_DEB }}"

- name: Create SMPlayer User Configuration Directory
  file:
    path: "{{ SMPLAYER_USER_CONF_DIR }}"
    state: "directory"

- name: Configure SMPlayer for User
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ SMPLAYER_USER }}"
    group: "{{ SMPLAYER_USER }}"
    mode: 0644
  with_items: "{{ SMPLAYER_USER_CONF_FILES }}"

- name: Remove SMPlayer Directories
  file:
    path: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item }}"
    state: "absent"
  with_items:
    - "{{ SMPLAYER_SOURCE }}"
    - "{{ SMPLAYER_THEMES_SOURCE }}"
    - "{{ SMPLAYER_SKINS_SOURCE }}"

- name: Remove SMPlayer Tarballs
  file:
    path: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item }}"
    state: "absent"
  with_items:
    - "{{ SMPLAYER_TARBALL }}"
    - "{{ SMPLAYER_THEMES_TARBALL }}"
    - "{{ SMPLAYER_SKINS_TARBALL }}"

- name: Remove SMPlayer DEB Packages
  file:
    path: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item }}"
    state: "absent"
  with_items:
    - "{{ SMPLAYER_DEB }}"
    - "{{ SMPLAYER_THEMES_DEB }}"
    - "{{ SMPLAYER_SKINS_DEB }}"
