---
# tasks file for SMPlayer
- name: Install Prerequisites
  apt:
    pkg: "{{ SMPLAYER_PREREQUISITES }}"
    state: "present"
    update_cache: "yes"

- name: Create SMPlayer Directories
  file:
    path: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item.name }}-{{ item.version }}"
    state: "directory"
  with_items: "{{ SMPLAYER }}"

- name: Download SMPlayer Tarballs
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.local_path }}"
  with_items: "{{ SMPLAYER }}"

- name: Extract SMPlayer Tarballs
  unarchive:
    src: "{{ item.local_path }}"
    dest: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item.name }}-{{ item.version }}"
    extra_opts:
      - "--strip-components=1"
  with_items: "{{ SMPLAYER }}"

- name: Create SMPlayer DEB Packages from Source
  shell: |
    ./create_deb.sh
  args:
    executable: "/bin/bash"
    chdir: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item.name }}-{{ item.version }}"
  with_items: "{{ SMPLAYER }}"

- name: Install SMPlayer DEB Packages
  shell: "dpkg --install {{ item }}"
  args:
    executable: "/bin/bash"
    chdir: "{{ SMPLAYER_SOURCE_PREFIX }}"
  with_items:
    - "{{ SMPLAYER_DEB }}"
    - "{{ SMPLAYER_THEMES_DEB }}"
    - "{{ SMPLAYER_SKINS_DEB }}"

- name: Create SMPlayer User Configuration Directory
  file:
    path: "{{ SMPLAYER_USER_CONF_DIR }}"
    state: "directory"

- name: Configure SMPlayer for User(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ SMPLAYER_USER }}"
    group: "{{ SMPLAYER_USER }}"
    mode: 0644
  with_items: "{{ SMPLAYER_USER_CONF_FILES }}"

- name: Remove SMPlayer Directories
  file:
    path: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item.name }}-{{ item.version }}"
    state: "absent"
  with_items: "{{ SMPLAYER }}"

- name: Remove SMPlayer Tarballs
  file:
    path: "{{ item.local_path }}"
    state: "absent"
  with_items: "{{ SMPLAYER }}"

- name: Remove SMPlayer DEB Packages
  file:
    path: "{{ SMPLAYER_SOURCE_PREFIX }}/{{ item }}"
    state: "absent"
  with_items:
    - "{{ SMPLAYER_DEB }}"
    - "{{ SMPLAYER_THEMES_DEB }}"
    - "{{ SMPLAYER_SKINS_DEB }}"
