dependencies: []
galaxy_info:
  author: Saad Ali
  description: Install SMPlayer
  license: license (MIT)
  min_ansible_version: 2.8
  platforms:
  - name: Debian
    versions:
      - stretch
      - buster
  galaxy_tags:
    - smplayer
