- name: Install Browsers
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Install Python for Ansible
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get -y install python)
      register: output
      changed_when: output.stdout != ""
    - setup:
  become: True
  roles:
    - Browsers